### ISSUE TITLE
Adding connection error

### ISSUE THREAD

**Issue by jorisvankessel** [naruxde/revpicommander#1]
First of all, you did a great job by developing this tool! 

The latest version (0.9.2) returns a crash of RevPiCommander when adding a connection. When pressing on the + the program stops. (Running on windows 10)

**Comment by naruxde** [comment]
We fixed that in 0.9.3. Sorry for the late response!

[commit](https://github.com/naruxde/revpicommander/commit/6bf453790ac42b3b2495ec4b96e5cebe451374d6)

#close
